version: "3.8"

services:
  e-shop:
    image: node:16-alpine
    container_name: "e-shop-express"
    working_dir: '/app'
    stdin_open: true
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=E-Shop
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    volumes:
      - db-data:/var/lib/psql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:
