version: "3.8"

services:
  e-shop:
    image: node:16-alpine
    container_name: "e-shop-express"
    working_dir: '/app'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8000:8000"